Repository EPFL-BIO-210/demo-project, pull requests merged in 2021-11, with the labels that each got.

#1 Feature/functionify
  .gitignore
  functions.py
  main.py
Labels: enhancement, new-feature

#2 Feature/stability
  .gitignore
  LotkaVolterraModel.py
  functions.py
  main.py
Labels: documentation, enhancement

#3 Feature/visualization
  LotkaVolterraModel.py
  Visualization.py
  graphs/rabbits_and_foxes_1.png
  main.py
Labels: enhancement, new-feature

#4 Feature/unittests
  LotkaVolterraModel.py
  README.md
  test_LVM.py
  tests.sh
Labels: documentation, enhancement, new-feature
